name: Python microservices test

on:
  push:
    branches: [main]
  pull_request:
    branches: "*"

jobs:
  test-quote-gen:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install Dependencies for quote-gen
        run: |
          cd quote_gen
          python -m pip install -r requirements.txt

      - name: Run tests for quote-gen
        run: |
          cd quote_gen
          python -m unittest discover -s tests

  test-quote-disp:
    needs: test-quote-gen
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install Dependencies for quote-disp
        run: |
          cd quote_disp
          python -m pip install -r requirements.txt

      - name: Run tests for quote-disp
        run: |
          cd quote_disp
          python -m unittest discover -s tests
